name: Build Front image
run-name: Build Front docker image

on:
  push:
    tags:
      - '1.*'
      - 'v1.*'

jobs:
  quasar-build:
    uses: ./.github/workflows/build-front.yml
    with:
      working-dir: .

  quasar-build-image:
    needs: quasar-build
    runs-on: ubuntu-latest

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Set Tag to Env
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event.ref) }}
        run: echo "GITHUB_TAG=$(echo $EVENT_CONTEXT | cut -d '/' -f 3 | cut -d '"' -f 1)" >> $GITHUB_ENV

      - name: Build docker
        run: docker build -f Dockerfile/Dockerfile  -t ${{ secrets.SCW_REGISTRY}}/a10cfront:${{env.GITHUB_TAG}} .

      - name: Docker push
        run: |
          docker login ${{ secrets.SCW_REGISTRY}} -u nologin --password-stdin <<< ${{ secrets.SCW_SECRET_KEY}}
          docker push ${{ secrets.SCW_REGISTRY}}/a10cfront:${{env.GITHUB_TAG}}
