name: Front CI
run-name: Front CI

on: [push]

defaults:
  run:
    working-directory: frontapp

jobs:
  quasar-build:
    uses: ./.github/workflows/build-front.yml
    with:
      working-dir: .
    secrets:
      fontawesome-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
